if(NOT DEFINED PLUGIN_FILE OR NOT EXISTS "${PLUGIN_FILE}")
    message(FATAL_ERROR "Release plugin does not exist: ${PLUGIN_FILE}")
endif()
foreach(required README.md LICENSE THIRD_PARTY_NOTICES.md CHANGELOG.md)
    if(NOT EXISTS "${SOURCE_DIR}/${required}")
        message(FATAL_ERROR "Required package file is missing: ${required}")
    endif()
endforeach()

set(package_name "AviUtl2LaTeX-v${PROJECT_VERSION}")
set(stage "${DIST_DIR}/stage/AviUtl2LaTeX")
set(archive "${DIST_DIR}/${package_name}.zip")
file(REMOVE_RECURSE "${DIST_DIR}/stage")
file(MAKE_DIRECTORY "${stage}")
file(COPY_FILE "${PLUGIN_FILE}" "${stage}/AviUtl2LaTeX.auf2" ONLY_IF_DIFFERENT)
foreach(document README.md LICENSE THIRD_PARTY_NOTICES.md CHANGELOG.md)
    file(COPY_FILE "${SOURCE_DIR}/${document}" "${stage}/${document}" ONLY_IF_DIFFERENT)
endforeach()
file(REMOVE "${archive}")
file(ARCHIVE_CREATE OUTPUT "${archive}" PATHS "${DIST_DIR}/stage/AviUtl2LaTeX"
    FORMAT zip WORKING_DIRECTORY "${DIST_DIR}/stage")
file(SHA256 "${archive}" digest)
file(WRITE "${DIST_DIR}/${package_name}.sha256" "${digest}  ${package_name}.zip\n")
message(STATUS "Created ${archive}")

